from pathlib import Path

import numpy as np
import pandas as pd


# Processed BHX annotation file generated by prepare_bhx_annotations.py
BOX_CSV = Path("/storage/student5/handt/bhx/bhx_selected_boxes_5class.csv")

# Output files will be saved directly in /storage/student5/handt/bhx/
OUT_DIR = Path("/storage/student5/handt/bhx")
OUT_DIR.mkdir(parents=True, exist_ok=True)

FULL_OUT = OUT_DIR / "bhx_boxes_5class_with_split.csv"
TRAIN_OUT = OUT_DIR / "bhx_train_boxes_5class.csv"
VAL_OUT = OUT_DIR / "bhx_val_boxes_5class.csv"

VAL_RATIO = 0.2
N_TRIES = 100000
SEED = 42

CLASSES = [
    "epidural",
    "intraparenchymal",
    "intraventricular",
    "subarachnoid",
    "subdural",
]


def main():
    if not BOX_CSV.exists():
        raise FileNotFoundError(f"BOX_CSV does not exist: {BOX_CSV}")

    df = pd.read_csv(BOX_CSV)

    print("Original data")
    print("Box rows:", len(df))
    print("Unique images:", df["SOPInstanceUID"].nunique())
    print("Unique studies:", df["StudyInstanceUID"].nunique())
    print("\nClass counts:")
    print(df["class_name"].value_counts())

    studies = sorted(df["StudyInstanceUID"].dropna().unique().tolist())
    n_studies = len(studies)

    n_val = int(round(n_studies * VAL_RATIO))
    n_train = n_studies - n_val

    print("\nTarget split")
    print("Train studies:", n_train)
    print("Val studies:", n_val)

    study_to_idx = {s: i for i, s in enumerate(studies)}
    class_to_idx = {c: i for i, c in enumerate(CLASSES)}

    # Matrix shape: [number of studies, number of classes]
    # Each cell stores the number of bounding boxes of a given class in a given study
    counts = np.zeros((n_studies, len(CLASSES)), dtype=np.int64)

    for _, row in df.iterrows():
        study = row["StudyInstanceUID"]
        cls = row["class_name"]

        if cls in class_to_idx:
            counts[study_to_idx[study], class_to_idx[cls]] += 1

    print("\nStudies per class:")
    for i, cls in enumerate(CLASSES):
        print(f"{cls}: {(counts[:, i] > 0).sum()} studies")

    total_counts = counts.sum(axis=0)
    target_val_counts = total_counts * VAL_RATIO
    target_train_counts = total_counts - target_val_counts

    rng = np.random.default_rng(SEED)

    best_score = float("inf")
    best_split = None

    # Higher weights are assigned to rarer or more important classes
    # Epidural is the rarest class, so it receives the highest weight
    weights = np.array([5.0, 1.5, 2.0, 1.0, 1.0], dtype=np.float32)

    for _ in range(N_TRIES):
        perm = rng.permutation(n_studies)

        val_idx = perm[:n_val]
        train_idx = perm[n_val:]

        val_counts = counts[val_idx].sum(axis=0)
        train_counts = counts[train_idx].sum(axis=0)

        # Hard constraint: both train and validation sets must contain all 5 classes
        if not (val_counts > 0).all():
            continue

        if not (train_counts > 0).all():
            continue

        # Score how close the split is to the target class distribution
        val_score = (
            ((val_counts - target_val_counts) / np.maximum(target_val_counts, 1.0)) ** 2
            * weights
        ).sum()

        train_score = (
            ((train_counts - target_train_counts) / np.maximum(target_train_counts, 1.0)) ** 2
            * weights
        ).sum()

        score = val_score + train_score

        if score < best_score:
            best_score = score
            best_split = (train_idx, val_idx, train_counts, val_counts)

    if best_split is None:
        raise RuntimeError(
            "Could not find a train/validation split containing all 5 classes. "
            "Increase N_TRIES or check the dataset distribution."
        )

    train_idx, val_idx, train_counts, val_counts = best_split

    train_studies = {studies[i] for i in train_idx}
    val_studies = {studies[i] for i in val_idx}

    # Check study-level leakage
    overlap = train_studies & val_studies
    print("\nOverlap studies:", len(overlap))
    assert len(overlap) == 0

    df["split"] = df["StudyInstanceUID"].apply(
        lambda s: "val" if s in val_studies else "train"
    )

    train_df = df[df["split"] == "train"].copy()
    val_df = df[df["split"] == "val"].copy()

    df.to_csv(FULL_OUT, index=False)
    train_df.to_csv(TRAIN_OUT, index=False)
    val_df.to_csv(VAL_OUT, index=False)

    print("\nSaved:")
    print(FULL_OUT)
    print(TRAIN_OUT)
    print(VAL_OUT)

    print("\nFINAL TRAIN")
    print("Box rows:", len(train_df))
    print("Unique images:", train_df["SOPInstanceUID"].nunique())
    print("Unique studies:", train_df["StudyInstanceUID"].nunique())
    print("Class counts:")
    print(train_df["class_name"].value_counts())

    print("\nFINAL VAL")
    print("Box rows:", len(val_df))
    print("Unique images:", val_df["SOPInstanceUID"].nunique())
    print("Unique studies:", val_df["StudyInstanceUID"].nunique())
    print("Class counts:")
    print(val_df["class_name"].value_counts())


if __name__ == "__main__":
    main()